export const Layers = {
	PRIMARY: "PRIMARY",
	BACKGROUND: "BACKGROUND", 
	HEALTHBARS: "HEALTHBARS",
	EXTRABARS: "EXTRABARS",
	UI: "UI",
	INFORMATION_BACKGROUND: "INFORMATION_BACKGROUND",
	STATES:"STATES"
} as const;