export const Layers = {
	PRIMARY: "PRIMARY",
	BACKGROUND: "BACKGROUND", 
	HEALTHBARS: "HEALTHBARS",
	EXTRABARS: "EXTRABARS",
	UI: "UI",
	INFORMATION_BACKGROUND: "INFORMATION_BACKGROUND",
	STATES:"STATES",
	GAMEEND:"GAMEEND",
	PAUSE: "PAUSE",
	CONTROLS: "CONTROLS",
	CONTROLS_BACKGROUND: "CONTROLS_BACKGROUND",
	PAUSE_BACKGROUND: "PAUSE_BACKGROUND",
} as const;